config/routes.rb
Erbv2::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :users
  resources :companies, path: 'our-customers' do
    member { get :snippet }
  end
  resources :posts, path: :news, defaults: { format: 'html' }
  resources :feeds
  resources :categories
  resources :boxes do
    collection { post :import }
    resources :unique_numbers, path: 'uin' do
      resources :locations
    end
  end
  resources :quotes, only: [:create]
  resources :orders
  resources :order_details
  resources :trips
  resources :sessions, only: [:new, :create, :destroy]
  resources :mailings, only: [:create, :index]
  resources :password_resets

  root                              to: 'pages#home'
  match '/company-profile',         to: 'pages#company-profile', as: :about
  match '/contact',                 to: 'pages#contact'
  match '/what-people-are-saying',  to: 'pages#testimonials', as: :testimonials
  match '/reusable-boxes',          to: 'pages#reusable-boxes', as: :reuse
  match '/methodology',             to: 'pages#methodology', as: :restore
  match '/sustainability',          to: 'pages#sustainability', as: :rethink
  match '/privacy',                 to: 'pages#privacy'
  match '/software',                to: 'pages#software'
  match '/use',                     to: 'pages#terms-of-use'
  match '/shipping-containers',     to: 'pages#shipping-containers', as: :shipping
  match '/tape',                    to: 'pages#tape'
  match '/signup',                  to: 'users#new'
  match '/signin',                  to: 'sessions#new'
  match '/signout',                 to: 'sessions#destroy', via: :delete
  match '/resources',               to: 'pages#resources'
  match '/savings',                 to: 'pages#cost-savings'
  match '/update-feed',             to: 'posts#feed', as: :update_feed
  match '/track',                   to: 'boxes#track', as: :track_box
  match '/erb',                     to: 'companies#erb'
  match '/calc',                    to: 'boxes#calc'
  match '/box-detail',              to: 'boxes#detail', as: :box_detail
  match '/import-locations',        to: 'locations#import', as: :import_locations

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  company_id             :integer
#  name                   :string(255)
#  email                  :string(255)
#  password_digest        :string(255)
#  remember_token         :string(255)
#  admin                  :boolean          default(FALSE)
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  subscribe              :boolean          default(TRUE)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :company_id, :admin, :subscribe,
                  :password, :password_confirmation
  has_secure_password

  belongs_to :company
  has_many :posts

  before_save { |user| user.email = email.downcase.strip }
  before_save :create_remember_token
  after_save :add_mailings

  validates :name, presence: true, length: { maximum: 50 }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def first_name
    self.name.split(' ').first
  end

private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    def add_mailings
      if self.subscribe?
        Mailing.create(email: self.email, name: self.name)
      else
        Mailing.where(email: self.email)[0].delete
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user,    only: [:index, :edit, :update, :show, 
                                           :destroy, :following, :followers]
  before_filter :correct_user,      only: [:edit, :update, :show]
  before_filter :admin_user,        only: [:destroy]

  def create
    @user = User.new(params[:user])
    @companies = Company.all
    if @user.save
      flash[:success] = "User created."
      redirect_to user_path(current_user, company_id: @user.company.id)
    else
      render 'users/new'
    end
  end

  def new
    @user = User.new
    @companies = Company.all
  end

  def show
    @user = User.find(params[:id])
    company_id = !params[:company_id].nil? ? params[:company_id] : 1
    @selected_company = company_id.to_i
    @companies = Company.all
    @company = current_user.admin? ? Company.find(company_id) : @user.company
    @since = @company.orders.any? ? @company.acquired : Date.today-7.day
    
    @trees = @company.trees
    @houses = (@trees/53).floor
    @water = @company.water
    @pools = (@water/20000).floor
    @electricity = @company.electricity
    @homes = (@electricity/12000).round(1)

    @orders = @company.orders
    @boxes = @company.boxes.order('created_at ASC')

    @count = @boxes.map { |b| b.in }.sum
    @trips = @boxes.map { |b| b.trip_count }.sum
    @inactive = @boxes.map { |b| b.out }.sum
    @active = @count - @inactive
    @avg = @trips / @count if @count > 0

    @cost = @boxes.map { |b| b.cost }.sum
    @yearly = (@cost / (Date.today - @since).to_i * 365).round

    @paper_cost = @company.orders.any? ? @boxes.map { |b| b.cb_cost }.sum : 1
    @yearly_cb = (@paper_cost / (Date.today - @since).to_i * 365).round
    
    @roi = @paper_cost - @cost
    @percent = (100 - @cost/@paper_cost * 100).round

    @purchase_array = []
    total = 0
    @company.orders.order('ordered_on ASC').each do |o|
      total += o.cost.to_f
      @purchase_array.append([(o.ordered_on.to_time.to_i.to_s+'000').to_i, total])
    end
    @purchase_array.append([(Date.today.to_time.to_i.to_s+'000').to_i, total])

    @mailings = Mailing.all

  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def index
    @users = User.page(params[:page]).per(10)
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in_user @user
      redirect_to @user
    else
      render 'users/edit'
    end
  end

  private
  
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 40 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def already_signed_in
    if signed_in?
      redirect_to root_path
      flash[:notice] = "You're already signed up!"
    end
  end
end

app/views/users/_manage_boxes.html.erb
<div class='tab-pane fade' id='boxes'>
  <div class='row'>
    <div class="col-md-3 col-md-offset-1 well">
      <table class="table table-hover">
        <thead><h2>Boxes</h2></thead>
        <tbody>
          <tr><td>Total Boxes purchased: <%= number_with_delimiter(@count) %></td></tr>
          <tr><td>Active: <%= number_with_delimiter(@active) %></td></tr>
          <tr><td>Retired: <%= number_with_delimiter(@inactive) %></td></tr>
          <tr><td>Total Trips: <%= number_with_delimiter(@trips) %></td></tr>
          <tr><td>Average Trips: <%= @avg %></td></tr>
        </tbody>
      </table>
      <%= link_to "Add Box", new_box_path(company_id: @company.id), class: "btn btn-success" if admin? %>
      <hr>
      <h4>Export Company Box List</h4>
      <%= link_to "Export CSV", boxes_path(format: "csv", company_id: @company.id), class: 'btn btn-info' %>
      <% if admin? %> 
        <hr>
        <h4>Import Unique Trips</h4>
        <%= form_tag import_locations_path, multipart: true do %>
          <div class="fileinput fileinput-new" data-provides="fileinput">
            <span class="btn btn-default btn-file">
              <span class="fileinput-new">
                Select file
              </span>
              <span class="fileinput-exists">
                Change
              </span>
              <%= file_field_tag :file %>
            </span>
            <span class="fileinput-filename"></span>
            <a class="close fileinput-exists" data-dismiss="fileinput" href="#" style="float: none">
              &times;
            </a>
          </div>
          <br/>
          <%= submit_tag 'Import Trips', class: 'btn btn-warning' %>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-7">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>name</th>
            <th>Active</th>
            <th>Retired</th>
            <th>Avg Trips</th>
          </tr>
        </thead>
        <tbody>
          <% @boxes.order('uid desc').each do |b| %>
            <% trips = b.trip_count %>
            <% count = b.in > 0 ? b.in : 1 %>
            <% retired = b.out %>
            <tr>
              <td><%= link_to b.uid, b %></td>
              <td><%= count - retired %></td>
              <td><%= retired %></td>
              <td><%= trips / count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<% if params[:page] %>
  <script>
    $(document).ready(function () {
      $('#myTab a[href="#boxes"]').tab('show');
    })
  </script>
<% end %>

app/views/users/_new.html.erb
<div class='tab-pane fade' id='add_user'>
  <div class='row'>
    <div class="col-md-3 col-md-offset-1 well">
      <table class="table table-hover">
        <thead><h2>Add User</h2></thead>
        <tbody>
          <tr><td>Total Users: <%= User.all.size %></td></tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-7">
      <%= form_for User.new, html: {class: 'form-horizontal', role: 'form'} do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class='form-group'>
          <%= f.label :name, class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.text_field :name, class: 'form-control' %>
            <div class="checkbox">
              <label>
                <%= f.check_box :admin %> User is an Admin?
              </label>
            </div>
            
          </div>
        </div>
        <div class='form-group'>
          <%= f.label :company_id, class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.collection_select :company_id, @companies, :id, :name,
                                            {include_blank: true, selected: @selected_company}, {class: 'form-control'} %>
          </div>
        </div>
        <div class='form-group'>                                  
          <%= f.label :email, class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
        <div class='form-group'>
          <%= f.label :password, class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
        </div>
        <div class='form-group'>
          <%= f.label :password_confirmation, "Confirm Password", class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>
        <div class='form-group'>
          <div class='col-sm-offset-2 col-sm-10'>
            <%= f.submit "Create User!", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>


app/views/users/_orders.html.erb
<div class='tab-pane fade' id='orders'>
  <div class='row'>
    <div class="col-md-3 col-md-offset-1 well">
      <table class="table table-striped">
        <thead><h2>Order History</h2></thead>
        <tbody>
          <tr><td><strong>Totals</strong></td></tr>
          <tr><td>Orders: <%= @orders.size %></td></tr>
        </tbody>
      </table>
      <%= link_to 'Add Order', new_order_url(company_id: @company.id), class: 'btn btn-success' if admin? %>
    </div>
    <div class="col-md-7">
      <table class="table table-striped table-bordered">
        <tr>
          <th>Invoice #</th>
          <th>Date ordered</th>
          <th>Date delivered</th>
          <th>Paid</th>
        </tr>
        <%- @orders.each do |o| %>
          <tr>
            <td><%= link_to o.invoice, o, target: '_blank' %></td>
            <td><%= o.ordered_on %></td>
            <td><%= o.delivered_on %></td>
            <td><%= o.paid ? "Yes" : "No" %></td>
          </tr>
        <%- end %>
      </table>
    </div>
  </div>
</div>

app/views/users/_overview.html.erb
<div class='tab-pane active fade in' id='overview'>
  <div class='row'>
    <div class="col-md-3 col-md-offset-1 well">
      <table class="table table-hover">
        <thead><h2>Stats Overview</h2></thead>
        <tbody>
          <tr><td><strong>Current</strong></td></tr>
          <tr><td>Active Boxes: <%= number_with_delimiter(@active) %></td></tr>
          <tr><td>Inactive Boxes: <%= number_with_delimiter(@inactive) %></td></tr>
          <tr><td>Trips per Box: ~<%= @avg %></td></tr>
          <tr><td><strong>Totals</strong></td></tr>
          <tr><td>ERB Packages: <%= number_with_delimiter(@count) %></td></tr>
          <tr><td>Unique Packages: <%= @boxes.size %></td></tr>
          <tr><td>Shipments sent: <%= number_with_delimiter(@trips) %></td></tr>
          <tr><td>Total Savings: <%= number_to_currency(@roi, precision: 0) %></td></tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-7">
      <table class="table">
        <thead><h2>Resource Savings</h2></thead>
        <tr><td><%= image_tag 'res_trees.png', alt: 'trees', class: 'resource_pic' %></td>
            <td><h1><%= "#{pluralize(number_with_delimiter(@company.trees), 'tree')}" %></h1></td></tr>
        <tr><td><%= image_tag 'res_water.png', alt: 'trees', class: 'resource_pic' %></td>
            <td><h1><%= "#{pluralize(number_with_delimiter(@company.water), 'gallon')} of water" %></h1></td></tr>
        <tr><td><%= image_tag 'res_energy.png', alt: 'trees', class: 'resource_pic' %></td>
            <td><h1><%= raw "#{number_with_delimiter(@company.electricity)} kW&#8226;h of electricity" %></h1></td></tr>
      </table>
    </div>
  </div>
</div>



app/views/users/_roi.html.erb
<div class='tab-pane fade' id='roi'>
  <div class='row'>
    <div class="col-md-3 col-md-offset-1 well">
      <table class="table table-hover">
        <thead><h2>Cost Overview</h2></thead>
        <tbody>
          <tr><td><strong>Yearly</strong></td></tr>
          <tr><td>Savings: <%= @percent %>% over cardboard</td></tr>
          <tr><td>ERB Costs: <%= number_to_currency(@yearly, precision: 0) %></td></tr>
          <tr><td>Cardboard Costs: <%= number_to_currency(@yearly_cb, precision: 0) %></td></tr>
          <tr><td><strong>Totals</strong></td></tr>
          <tr><td>Member since: <%= @since.strftime('%B %Y') %></td></tr>
          <tr><td>ERB Cost: <%= number_to_currency(@cost, precision: 0) %></td></tr>
          <tr><td>Cardboard Cost: <%= number_to_currency(@paper_cost, precision: 0) %></td></tr>
          <tr><td>Total Savings: <%= number_to_currency(@roi, precision: 0) %></td></tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-7">
      <strong>Cost Savings by switching to Eco ReBox</strong>
      <br/><br/>
      <div id="placeholder" style="width:575px;height:300px;"></div>
      <p id='plotV'></p>

      <script type="text/javascript">
        $(function () {
          var erb = <%= @purchase_array %>;
          var cb = [[<%= @since.to_time.to_i %>000, 0],
                    [<%= Date.today.to_time.to_i %>000, <%= @paper_cost %>]]
          $.plot($("#placeholder"), 
            [ { data: erb, label: "Eco ReBox Cost", lines: {steps: true}, color: "#ccc" }, 
              { data: cb, label: "Savings over Cardboard", color: "#b8d18f" } ], {
            yaxis: {
              tickFormatter: function (v, axis) { 
                return '$' + v
              },
              labelWidth: 60,
              labelHeight: 20,
              reserveSpace: true
            },
            xaxis: {
              mode: "time",
              timeformat: "%m/%Y",
              minTickSize: [1, "month"],
              min: (new Date(<%= @since.strftime('%Y,%m,%d') %>)).getTime(),
              max: (new Date()).getTime()
            },
            grid: {
              backgroundColor: { colors: ["#fff", "#eee"] }
            },
            legend: { 
              position: 'nw' 
            }
          });
        });
      </script>
    </div>
  </div>
</div>

app/views/users/_snippet.html.erb
<div class='tab-pane fade' id='snippet'>
  <div class='row'>
    <div class="col-md-3 col-md-offset-1 well">
      <table class="table table-hover">
        <thead><h2>Public Snippet</h2></thead>
        <tbody>
          <tr><td>Copy and paste this code into the html file that you would like to display your resource savings on.</td></tr>
          <% if admin? %>
            <tr><td><%= link_to 'Company Snippet', erb_path, class: 'btn btn-primary', target: '_blank' %></td></tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-7">
      <xmp>
        <div id='erb_widget_container'></div>
        <script type="text/javascript">
          // JSON parser
          function fetchJSONFile(path, callback) {
            var httpRequest = new XMLHttpRequest();
            httpRequest.onreadystatechange = function() {
              if (httpRequest.readyState === 4) {
                if (httpRequest.status === 200) {
                  var data = JSON.parse(httpRequest.responseText);
                  if (callback) callback(data);
                };
              };
            };
            httpRequest.open('GET', path);
            httpRequest.send();
          }
          // formatting helper
          function numberWithCommas(x) {
            var parts = x.toString().split(".");
            parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",");
            return parts.join(".");
          }

          // this requires the file and executes a callback with the parsed result once available
          fetchJSONFile('http://www.ecorebox.com/our-customers/<%= @company.id %>/snippet.json', function(data){
            // resource savings
            var trees = numberWithCommas(data['trees']);
            var water = numberWithCommas(data['water']);
            var energy = numberWithCommas(data['electricity']);

            // this builds all the divs
            var widget = document.createElement("div");
            widget.id = 'erb_widget';
            widget.style.width = "200px";
            widget.style.height = "400px";
            widget.style.src = "local('Oswald Light'), local('Oswald-Light'), url(http://themes.googleusercontent.com/static/fonts/oswald/v7/HqHm7BVC_nzzTui2lzQTDT8E0i7KZn-EPnyo3HZu7kw.woff) format('woff')";
            widget.style.fontFamily = 'Oswald, sans-serif';
            widget.style.color = '#666';
            widget.style.border = 'solid 1px #666';

            var logo = document.createElement("div");
            logo.id = 'erbw_logo';
            logo.style.background = "url(http://www.ecorebox.com/assets/narrow_200px_logo.png) no-repeat";
            logo.style.height = '29px';
            logo.style.width = '109px';
            logo.style.margin = '20px auto';

            var txt = document.createElement("div");
            txt.id = 'erbw_txt';
            txt.style.font = 'bold 13px inherit';
            txt.style.margin = '5px';

            var cs_trees = document.createElement("div");
            cs_trees.id = 'erbw_cs_trees';
            cs_trees.style.background = "url(http://www.ecorebox.com/assets/erbw_ico_tree.png) no-repeat";
            cs_trees.style.height = '61px';
            cs_trees.style.margin = '20px';
            cs_trees.innerHTML = "<div style='margin: 12px auto auto 62px; font: 14px bold inherit;'><span style='font: 22px bolder'>" + trees + "</span><br/>Trees Saved</div>";

            var cs_water = document.createElement("div");
            cs_water.id = 'erbw_cs_water';
            cs_water.style.background = "url(http://www.ecorebox.com/assets/erbw_ico_water.png) no-repeat";
            cs_water.style.height = '61px';
            cs_water.style.margin = '20px';
            cs_water.innerHTML = "<div style='margin: 12px auto auto 52px; font: 14px bold inherit;'><span style='font: 22px bolder'>" + water + "</span><br/>Gallons of Water Conserved</div>";

            var cs_energy = document.createElement("div");
            cs_energy.id = 'erbw_cs_energy';
            cs_energy.style.background = "url(http://www.ecorebox.com/assets/erbw_ico_energy.png) no-repeat";
            cs_energy.style.height = '61px';
            cs_energy.style.margin = '20px';
            cs_energy.innerHTML = "<div style='margin: 12px auto auto 62px; font: 14px bold inherit;'><span style='font: 22px bolder'>" + energy + "</span><br/>kWh Energy Saved</div>";

            var footer = document.createElement("div");
            footer.id = 'erbw_footer';
            footer.style.font = 'bolder 14px';
            footer.style.textAlign = 'center';
            footer.style.padding = '10px';
            footer.style.margin = '10px';
            footer.innerHTML = "Learn more at<br/><a href='http://www.ecorebox.com' target='_blank'>www.ecorebox.com</a><br/>(858) 571-3638";

            document.getElementById('erb_widget_container').appendChild(widget);

            // this appends each of the children divs to the main widget
            document.getElementById('erb_widget').appendChild(logo);
            document.getElementById('erb_widget').appendChild(txt);
            document.getElementById('erb_widget').appendChild(cs_trees);
            document.getElementById('erb_widget').appendChild(cs_water);
            document.getElementById('erb_widget').appendChild(cs_energy);
            document.getElementById('erb_widget').appendChild(footer);
          });
        </script>
      </xmp>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="jumbotron">
  <div class="container">
    <h1>Update your profile</h1>
  </div>
</div>
<div class='container'>
<%= form_for @user, html: {class: 'form-horizontal', role: 'form'} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class='form-group'>
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class='col-sm-5'>
      <%= f.text_field :name, class: 'form-control' %>
      <% if admin? %>
        <div class="checkbox">
          <label>
            <%= f.check_box :admin %> User is an Admin?
          </label>
        </div>
      <% end %>
      <div class="checkbox">
        <label>
          <%= f.check_box :subscribe %> Subscribe to Updates
        </label>
      </div>
    </div>
  </div>
  <div class='form-group'>
    <%= f.label :company_id, class: 'col-sm-2 control-label' %>
    <div class='col-sm-5'>
      <%= f.collection_select :company_id, Company.all, :id, :name,
                                    {include_blank: true}, {class: 'form-control'} %>
    </div>
  </div>
  <div class='form-group'>                                  
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class='col-sm-5'>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class='form-group'>
    <%= f.label :password, class: 'col-sm-2 control-label' %>
    <div class='col-sm-5'>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
  </div>
  <div class='form-group'>
    <%= f.label :password_confirmation, "Confirm Password", class: 'col-sm-2 control-label' %>
    <div class='col-sm-5'>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
  </div>
  <div class='form-group'>
    <div class='col-sm-offset-2 col-sm-5'>
      <%= f.submit "Update User!", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

<script type="text/javascript">
  $('.dropdown.sixth').addClass('active');
</script>    

app/views/users/show.html.erb
<% provide(:title, "#{current_user.name}") %>
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <h1><%= link_to "#{@company.name}", @company %></h1>
        <p><%= current_user.name %></p>
      </div>

      <% if current_user.admin? %>
        <div class="col-sm-6 form-group">
          <%= form_for user_path(current_user), method: 'get', html: {class: 'form-horizontal', role: 'form'} do |f| %>
            <%= f.label "Select Company", class: 'col-sm-5 control-label' %>
            <div class='col-sm-7'>
              <%= f.collection_select :company_id, @companies, :id, :name,
                                      {selected: @selected_company}, { name: "company_id", onchange: "this.form.submit()", class: 'form-control user_select_company'} %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>      
<div class='container'>
  <ul class="nav nav-tabs" id='myTab'>
    <li class='active'><a href="#overview" data-toggle="tab">Resource Savings</a></li>
    <li><a href="#roi" data-toggle="tab">Cost Savings</a></li>
    <li><a href="#boxes" data-toggle="tab">Boxes</a></li>
    <li><a href="#orders" data-toggle="tab">Orders</a></li>
    <li><a href="#snippet" data-toggle="tab">Snippet</a></li>
    <% if admin? %>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          Admin <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#company_info" data-toggle="tab">Company Info</a></li>
          <li><a href="#add_user" data-toggle="tab">Add User</a></li>
          <li><a href="#subscription_list" data-toggle="tab">Subscriptions</a></li>
        </ul>
      </li>
    <% end %>
  </ul>
  <div class='tab-content'>
    <%= render 'overview' %>
    <%= render 'roi' %>
    <%= render 'manage_boxes' %>
    <%= render 'orders' %>
    <%= render 'snippet' %>
    <% if admin? %>
      <%= render 'companies/edit' %>
      <%= render 'new' %>
      <%= render 'mailings/mailings' %>
    <% end %>
  </div>
</div>

<script>
  $('.dropdown.sixth').addClass('active');
</script>