config/routes.rb
Erbv2::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :users
  resources :companies, path: 'our-customers' do
    member { get :snippet }
  end
  resources :posts, path: :news, defaults: { format: 'html' }
  resources :feeds
  resources :categories
  resources :boxes do
    collection { post :import }
    resources :unique_numbers, path: 'uin' do
      resources :locations
    end
  end
  resources :quotes, only: [:create]
  resources :orders
  resources :order_details
  resources :trips
  resources :sessions, only: [:new, :create, :destroy]
  resources :mailings, only: [:create, :index]
  resources :password_resets

  root                              to: 'pages#home'
  match '/company-profile',         to: 'pages#company-profile', as: :about
  match '/contact',                 to: 'pages#contact'
  match '/what-people-are-saying',  to: 'pages#testimonials', as: :testimonials
  match '/reusable-boxes',          to: 'pages#reusable-boxes', as: :reuse
  match '/methodology',             to: 'pages#methodology', as: :restore
  match '/sustainability',          to: 'pages#sustainability', as: :rethink
  match '/privacy',                 to: 'pages#privacy'
  match '/software',                to: 'pages#software'
  match '/use',                     to: 'pages#terms-of-use'
  match '/shipping-containers',     to: 'pages#shipping-containers', as: :shipping
  match '/tape',                    to: 'pages#tape'
  match '/signup',                  to: 'users#new'
  match '/signin',                  to: 'sessions#new'
  match '/signout',                 to: 'sessions#destroy', via: :delete
  match '/resources',               to: 'pages#resources'
  match '/savings',                 to: 'pages#cost-savings'
  match '/update-feed',             to: 'posts#feed', as: :update_feed
  match '/track',                   to: 'boxes#track', as: :track_box
  match '/erb',                     to: 'companies#erb'
  match '/calc',                    to: 'boxes#calc'
  match '/box-detail',              to: 'boxes#detail', as: :box_detail
  match '/import-locations',        to: 'locations#import', as: :import_locations

end

app/models/box.rb
# == Schema Information
#
# Table name: boxes
#
#  id         :integer          not null, primary key
#  company_id :integer
#  uid        :string(255)
#  length     :decimal(, )
#  width      :decimal(, )
#  height     :decimal(, )
#  weight     :decimal(, )
#  cost       :decimal(6, 2)
#  cb_cost    :decimal(6, 2)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  frequency  :integer
#  active     :boolean
#  multiplier :integer          default(1)
#

class Box < ActiveRecord::Base
  extend FriendlyId
  friendly_id :uid

  attr_accessible :company_id, :uid, :length, :width, :height,
                  :weight, :frequency, :retire, :multiplier, :active, :locations_count

  belongs_to :company
  has_many :trips
  has_many :unique_numbers
  has_many :order_details

  before_save { |box| box.uid = uid.strip }

  validates :uid, presence: true,
                  length: { maximum: 20 },
                  uniqueness: { case_sensitive: false }
  validates :company_id, :length, :width, :height, :weight, :frequency, presence: true

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |box|
        csv << box.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    #number of boxes updated
    ct = 0

    CSV.foreach(file.path, headers: true) do |row|
      if row['uid']
        box = find_by_id(row["id"]) || new
        box.attributes = row.to_hash.slice(*accessible_attributes)
        box.save!
        puts "#{box.uid} updated"
        ct += 1
      else
        puts "Box not modified, skipping"
      end
    end
    ct
  end

  # how many of a particular box has been ordered
  def in
    OrderDetail.find_all_by_box_id(self.id).map{ |d| d.quantity }.sum
  end

  # how many times a particular box has been shipped
  def out
    self.trips.map{ |t| t.retired }.sum
  end

  def trip_count
    self.trips.map{ |t| t.quantity }.sum
  end

  def cost
    OrderDetail.find_all_by_box_id(self.id).map{ |d| d.box_price * d.quantity }.sum
  end

  def cb_cost
    OrderDetail.find_all_by_box_id(self.id).map{ |d| d.cb_price * d.box.trip_count }.sum / self.multiplier
  end

  def date
    self.created_at.to_date
  end

  def trees
    w = self.trips.map{ |t| t.quantity }.sum * self.weight / self.multiplier
    (w * 0.00133).round(1)
  end

  def water
    w = self.trips.map{ |t| t.quantity }.sum * self.weight / self.multiplier
    (w * 5.3).round
  end

  def electricity
    w = self.trips.map{ |t| t.quantity }.sum * self.weight / self.multiplier
    (w * 8.687).round
  end

  def self.update_trips
    Box.where(active: true).each do |box|
      if !box.trips.map{|t| t.month.strftime('%Y-%m-01')}.include?(Date.today.strftime('%Y-%m-01'))
        box.trips.build(month: (Date.today+3.days).strftime('%Y-%m-01'), quantity: box.frequency, retired: box.retire).save
      end
    end
  end

  def update_trips(month)
    m = month.strftime('%Y-%m-01')
    if !self.trips.map{|t| t.month.strftime('%Y-%m-01')}.include?(m)
      self.trips.build(month: m, quantity: self.frequency, retired: self.retire).save
    else
      self.errors.add :trips, "#{month.strftime('%B %Y')} already exists"
    end
  end

  private

end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  respond_to :html, :json, :js
  require 'open-uri'

  def calc
    boxes_per_week = params[:boxes].to_f #boxes shipped per week
    # turn_time = params[:shipments].to_i #turn time in days
    shipments_per_year = 365
    life_of_box = 10 #life cycle of a box (10 trips)
    # ss = 1.1 #safety stock (10%)
    case params[:size].to_i
      when 1
        sa = 148 #surface area of box
        cb = 0.25 #cost of cardboard
        erb = 1.25 #cost of Eco ReBox
      when 2
        sa = 1152
        cb = 1
        erb = 5
      when 3
        sa = 2240
        cb = 2
        erb = 10
      when 4
        sa = 5232
        cb = 4.5
        erb = 22.5
    end

    # ERB box quantity
    @erb_q = (boxes_per_week/7*shipments_per_year/life_of_box).ceil

    # cardboard box quantity
    @cb_q = boxes_per_week*52

    # cb cost - erb cost
    @savings = (@cb_q*cb) - (@erb_q*erb)

    respond_with(@savings, @erb_q, @cb_q)
  end

  def create
    @box = Box.new(params[:box])
    @company = Company.find(params[:box][:company_id])
    if @box.save
      flash[:success] = "Box #{@box.uid} added!"
      redirect_to user_path(current_user, company_id: @company.id)
    else
      render 'boxes/new'
    end
  end

  def import
    count = Box.import(params[:file])
    if count > 0
      flash[:success] = "#{count} boxes updated!"
    else
      flash[:error] = "No boxes modified..."
    end
    redirect_to root_path
  end

  def index
    @company = Company.find(params[:company_id])
    @export = @company.boxes.order(:uid)
    respond_to do |format|
      format.html
      format.csv { send_data @export.to_csv, filename: "#{@company.name} Eco ReBoxes.csv" }
    end
  end

  def new
    @box = Box.new
    @company = Company.find(params[:company_id])
  end

  def show
    @box = Box.find(params[:id])
    cb = OrderDetail.find_all_by_box_id(@box.id).map{ |d| d.cb_price }
    @cb = cb.inject(:+).to_f / cb.size
    @new_uin = @box.unique_numbers.build
    @m = [*1..12]
    @y = [*2010..Date.today.year]
  end

  def track
    @uin = UniqueNumber.where(uin: params[:uin].upcase)[0]
    redirect_to [@uin.box, @uin] if @uin
  end

  def update
    @box = Box.find(params[:id])
    @box.update_attributes(params[:box])
    respond_with @box
  end

end

app/views/boxes/_calc.html.erb
<p>
  You could be saving around <br><b><%= number_to_currency(@savings, precision: 0) %> per year</b> by switching to Eco ReBox! <p>You'll only need <%= @erb_q %> ecoreboxes versus <%= @cb_q %>  cardboard boxes.
</p>

app/views/boxes/_track.html.erb
<%= form_tag track_box_path, class: 'input-group', id: 'track_a_box' do %>
  <%= text_field_tag :uin, nil, placeholder: 'Track Your Eco ReBox', class: 'form-control' %>
  <span class='input-group-btn'>
    <%= submit_tag "Track", class: 'btn btn-default' %>
  </span>
<% end %>

app/views/boxes/calc.js.erb
 $('#quick_calc').html("<%= j render partial: 'boxes/calc' %>");

app/views/boxes/new.html.erb
<% provide(:title, 'Add Box') %>
<div class="jumbotron">
  <div class="container">
    <h1>Add box</h1>
    <p>Current boxes: <%= @company.boxes.map(&:uid).to_sentence %></p>
  </div>
</div>
<div class='container'>
  <div class='row well'>
    <%= form_for @box, html:{class: 'form-horizontal', role: 'form'} do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class='col-sm-6'>
        <div class='form-group'>  
          <%= f.label :company_id, class: 'col-sm-6 control-label' %>
          <div class='col-sm-6'>
            <%= text_field_tag :company, @company.name, class: 'form-control', disabled: true %>
            <%= f.hidden_field :company_id, value: @company.id %>
            <%= f.hidden_field :active, value: true %>
          </div>
        </div>
        <div class='form-group'>
          <%= f.label :uid, 'Box name', class: 'col-sm-6 control-label' %>
          <div class='col-sm-6'>
            <%= f.text_field :uid, class: 'form-control' %>
          </div>
        </div>
        <div class='form-group'>
          <%= f.label :frequency, 'Shipments per month', class: 'col-sm-6 control-label' %>
          <div class='col-sm-6'>
            <%= f.text_field :frequency, class: 'form-control' %>
          </div>
        </div>
        <div class='form-group'>
          <div class='col-sm-offset-8'>
            <%= f.submit 'Add Box', class: "btn btn-large btn-primary" %>
            <%= link_to 'Cancel', user_path(current_user, company_id: @company.id), class: 'btn btn-default btn-sm' %>
          </div>
        </div>
      </div>
      <div class='col-sm-6'>
        <div class='form-group'>
          <%= f.label :length, class: 'col-sm-2 control-label' %>
          <div class='col-sm-6'>
            <%= f.text_field :length, class: 'form-control' %>
          </div>
        </div>
        <div class='form-group'>
          <%= f.label :width, class: 'col-sm-2 control-label' %>
          <div class='col-sm-6'>
            <%= f.text_field :width, class: 'form-control' %>
          </div>
        </div>
        <div class='form-group'>
          <%= f.label :height, class: 'col-sm-2 control-label' %>
          <div class='col-sm-6'>
            <%= f.text_field :height, class: 'form-control' %>
          </div>
        </div>
        <div class='form-group'>
          <%= f.label :weight, class: 'col-sm-2 control-label' %>
          <div class='col-sm-6'>
            <%= f.text_field :weight, class: 'form-control' %>
          </div>
        </div>
      </div>        
    <% end %>
  </div>
</div>

app/views/boxes/show.html.erb
<% provide(:title, @box.uid) %>
<div class="jumbotron">
  <div class="container">
    <h1>Box <%= @box.uid %></h1>
    <p>ReThink. ReStore. ReUse.</p>
  </div>
</div>
<div class='container'>
  <div class='row'>
    <div class="col-sm-4 col-sm-offset-1">
      <h3>Box properties</h3>
      <p><%= best_in_place_if admin?, @box, :length %>in x <%= best_in_place_if admin?, @box, :width %>in x <%= best_in_place_if admin?, @box, :height %>in and <%= best_in_place_if admin?, @box, :weight %>lbs</p>
      <p>Comparable cardboard box price: <%= number_to_currency(@cb) %></p>
      <p><%= @box.in %> total purchased</p>
      <p><%= @box.in - @box.out %> currently in rotation</p>
    </div>
    <div class="col-sm-4 col-sm-offset-2">
      <h3>Status <small>(editable)</small></h3>
      <p>Box ID: <span class='edit'><%= best_in_place_if (admin? || owner?), @box, :uid %></span></p>
      <p>Multiplier (if cardboard box was used multiple times, then how many?): <span class='edit'><%= best_in_place_if (admin? || owner?), @box, :multiplier %></span></p>
      <p class='wide'>Active? <span class='edit'><%= best_in_place_if (admin? || owner?), @box, :active, type: :checkbox %></span></p>
      <p class='wide'>Shipments per month: <span class='edit'><%= best_in_place_if (admin? || owner?), @box, :frequency %></span></p>
      <p class='wide'>Retired per month: <span class='edit'><%= best_in_place_if (admin? || owner?), @box, :retire %></span></p>
    </div>
  </div>

  <div class='row'>
    <div class="col-sm-6 col-xs-12 well">
      <h3>Unique Numbers</h3>
      <table id="companyBoxList" class="table table-striped table-bordered" data-source="<%= box_unique_numbers_url(format: "json", box_id: @box.id) %>">
        <thead>
          <tr>
            <th>UIN</th>
            <th>Active</th>
            <th>Trips</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
      <br/>
      <% if admin? %>
        <h4>Add Unique Identifying Numbers</h4>
        <%= form_for [@box, @new_uin], html: {class: 'form-inline', role: 'form'} do |f| %>
          <div class='form-group'>
            <%= label_tag :start, nil, class: 'sr-only' %>
            <%= text_field_tag :start, nil, placeholder: 'Starting UIN', class: 'form-control' %>
          </div>
          <div class='form-group'>
            <%= label_tag :quantity, nil, class: 'sr-only' %>
            <%= text_field_tag :quantity, nil, placeholder: 'quantity', class: 'form-control', style: 'width:75px' %>
          </div>
          <%= f.submit 'Add UINs', class: 'btn btn-success' %>
        <% end %>
      <% end %>
    </div>
    <div class="col-sm-6 col-xs-12 well">
      <h3>Trip History <small>(editable)</small></h3>
      <table class="table table-striped table-bordered trips">
        <thead>
          <tr>
            <th>Month</th>
            <th>Shipped</th>
            <th>Retired</th>
          </tr>
        </thead>
        <tbody>
          <% @box.trips.order('month desc').each do |t| %>
            <tr>
              <td>
                <%= t.month.strftime('%B %Y') %>
                <% if admin? %>
                  <span class='actions'>
                    <%= link_to '', t, method: :delete, data: { confirm: "You're sure you want to DELETE #{t.month.strftime('%B %Y')}'s trips?" }, class: 'glyphicon glyphicon-remove remove action', title: 'Delete Month' %>
                  </span>
                <% end %>
              </td>
              <td class='edit'><%= best_in_place_if (admin? || owner?), t, :quantity %></td>
              <td class='edit'><%= best_in_place_if (admin? || owner?), t, :retired %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% if admin? %>
        <h4>Manually add a Month</h4>
        <%= form_for Trip.new, html: {class: 'form-inline', role: 'form'} do |f| %>
          <div class='form-group'>
            <%= label_tag :month, nil, class: 'sr-only' %>
            <%= select_month Date.today, {}, class: 'form-control' %>
          </div>
          <div class='form-group'>
            <%= label_tag :year, nil, class: 'sr-only' %>
            <%= select_year Date.today, {start_year: 2010, end_year: Date.today.year}, class: 'form-control' %>
          </div>
          <%= hidden_field_tag :box_id, @box.id %>
          <div class='form-group'>
            <%= f.submit 'Add Month', class: 'btn btn-success' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/boxes/track.html.erb
<div class='container'>
  <div id='tracker'>
    <div id="contact_tracking_view" class='container'>
      <h2>Nothing matches our records, please search again.</h2>
      <div class='col-sm-4 col-sm-offset-4 bottom'>     
        <%= render 'boxes/track' %>
      </div>
    </div>
  </div>
</div>