config/routes.rb
Erbv2::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :users
  resources :companies, path: 'our-customers' do
    member { get :snippet }
  end
  resources :posts, path: :news, defaults: { format: 'html' }
  resources :feeds
  resources :categories
  resources :boxes do
    collection { post :import }
    resources :unique_numbers, path: 'uin' do
      resources :locations
    end
  end
  resources :quotes, only: [:create]
  resources :orders
  resources :order_details
  resources :trips
  resources :sessions, only: [:new, :create, :destroy]
  resources :mailings, only: [:create, :index]
  resources :password_resets

  root                              to: 'pages#home'
  match '/company-profile',         to: 'pages#company-profile', as: :about
  match '/contact',                 to: 'pages#contact'
  match '/what-people-are-saying',  to: 'pages#testimonials', as: :testimonials
  match '/reusable-boxes',          to: 'pages#reusable-boxes', as: :reuse
  match '/methodology',             to: 'pages#methodology', as: :restore
  match '/sustainability',          to: 'pages#sustainability', as: :rethink
  match '/privacy',                 to: 'pages#privacy'
  match '/software',                to: 'pages#software'
  match '/use',                     to: 'pages#terms-of-use'
  match '/shipping-containers',     to: 'pages#shipping-containers', as: :shipping
  match '/tape',                    to: 'pages#tape'
  match '/signup',                  to: 'users#new'
  match '/signin',                  to: 'sessions#new'
  match '/signout',                 to: 'sessions#destroy', via: :delete
  match '/resources',               to: 'pages#resources'
  match '/savings',                 to: 'pages#cost-savings'
  match '/update-feed',             to: 'posts#feed', as: :update_feed
  match '/track',                   to: 'boxes#track', as: :track_box
  match '/erb',                     to: 'companies#erb'
  match '/calc',                    to: 'boxes#calc'
  match '/box-detail',              to: 'boxes#detail', as: :box_detail
  match '/import-locations',        to: 'locations#import', as: :import_locations

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer          not null, primary key
#  feed_id      :integer
#  user_id      :integer
#  title        :string(255)
#  author       :string(255)
#  url          :string(255)
#  summary      :text
#  content      :text
#  guid         :string(255)
#  published_at :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  slug         :string(255)
#

class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  attr_accessible :user_id, :feed_id, :title, :summary, :url, :content, :author,
                  :category_tokens, :published_at, :guid
  attr_reader :category_tokens

  belongs_to :user
  belongs_to :feed
  has_many :tags, dependent: :destroy
  has_many :categories, through: :tags

  validates :content, presence: true

  default_scope order: 'posts.published_at DESC'

  def category_tokens=(tokens)
    self.category_ids = Category.ids_from_tokens(tokens)
  end

  def self.update_from_feed(feed_url, feed_id)
    feed = Feedjira::Feed.fetch_and_parse(feed_url)
    add_entries(feed.entries, feed_id)
  end

  def self.update_from_feed_continuously(feed_url, delay_interval = 15.minutes)
    feed = Feedjira::Feed.fetch_and_parse(feed_url)
    add_entries(feed.entries)
    loop do
      sleep delay_interval
      feed = Feedjira::Feed.update(feed)
      add_entries(feed.new_entries) if feed.updated?
    end
  end

  private

    def self.add_entries(entries, feed_id)
      entries.each do |entry|
        unless exists? guid: entry.id
          current = Category.all.map {|c| c.name}
          incoming = entry.categories.map!{|c| c.downcase.strip}
          (incoming - current).each do |tag|
            Category.create(name: tag)
          end
          create!(
            feed_id:            feed_id,
            title:              entry.title,
            content:            entry.content,
            summary:            entry.summary,
            url:                entry.url,
            published_at:       entry.published,
            guid:               entry.id,
            author:             entry.author,
            category_tokens:    Category.where("name IN (?)", incoming).map{|c| c.id}.join(',')
          )
        end
      end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy, :feed]
  before_filter :check_for_cancel, only: [:create, :update]

  def create
    params[:post][:published_at] = Time.current()
    params[:post][:guid] = "ERBlog-" + ('a'..'z').to_a.shuffle[0,8].join
    params[:post][:feed_id] = 1
    params[:post][:author] = current_user.name
    @post = current_user.posts.build(params[:post])
    if @post.save
      @post.update_attributes(url: "http://ecorebox.com/news/#{@post.id}")
      flash[:success] = "Blog entry created!"
      redirect_to posts_path
    else
      flash[:error] = "Something went wrong there... try again."
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Blog entry deleted!"
    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def feed
    before = Post.all.size
    Feed.all.reject{ |f|f.id == 1 }.each do |feed|
      Post.update_from_feed(feed.feed_url, feed.id)
    end
    after = Post.all.size
    if after - before > 0
      flash[:success] = "Blog updated with #{after - before} entries!"
    else
      flash[:notice] = "Nothing to update..."
    end
    redirect_to posts_path
  end

  def index
    # this will be the name of the feed displayed on the feed reader
    @title = "Eco ReBoxing"
    # the news items
    @posts = Post.page(params[:page]).per(10)
    # this will be our Feed's update timestamp
    @updated = @posts.first.updated_at unless @posts.empty?

    respond_to do |format|
      format.html
      format.atom { render layout: false }
      # we want the RSS feed to redirect permanently to the ATOM feed
      format.rss { redirect_to posts_path(format: :atom), status: :moved_permanently }
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @categories = @post.categories
    @user = @post.user ? @post.user.name : @post.author
    @published = @post.published_at ? @post.published_at : @post.created_at
    set_meta_tags og: {
      title: @post.title,
      type: 'article',
      url: post_url(@post),
      image: Nokogiri::HTML(@post.content).css('img').map{ |i| i['src']},
      article: {
        published_time: @published.to_datetime,
        modified_time: @post.updated_at.to_datetime,
        author: @user,
        section: 'News',
        tag: @categories.map(&:name)
      }
    }
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      flash[:success] = "Blog Entry updated!"
      redirect_to @post
    else
      flash[:error] = "Something went wrong there... try again."
      render 'posts/edit'
    end
  end

  private

    def check_for_cancel
      if params[:commit] == "Cancel"
        redirect_to posts_path
      end
    end

    def correct_user
      @post = current_user.posts.find_by_id(params[:id])
      redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def parse_links(comment)
    auto_link(comment, html: {target: '_blank', class: 'link'}) do |text|
      URI.parse(text).host
    end
  end
end

app/views/posts/_add.html.erb
<%= form_for Feed.new do |f| %>
  <%= text_field_tag :feed_url, nil, placeholder: 'Feed URL', style: 'width:300px', class: 'form-control' %>
  <%= f.submit 'Add feed', class: 'btn' %>
<% end %>

app/views/posts/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class='form-group'>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'tf_blog form-control' %>
</div>
<div class='form-group'>
  <%= f.label :summary, 'Summary (if blank, Content will just be summarized)' %>
  <%= f.text_field :summary, class: 'tf_blog2 form-control' %>
</div>
<div class='form-group'>
  <%= f.label :content %>
  <%= f.cktext_area :content, ckeditor: {}, class: 'form-control' %>
</div>
<br/>
<div class='form-group'>
  <%= f.label :category_tokens, "Categories" %>
  <%= f.text_field :category_tokens, data: {load: @post.categories}, class: 'form-control' %>
</div>

app/views/posts/_post.html.erb
<div class='post_index'>
  <h3><%= link_to post.title, post, class: 'green' %><br/>
    <small>posted <%= time_ago_in_words(post.published_at ? post.published_at : post.created_at) %> ago by <%= post.user ? post.user.name : post.author %></small>
  </h3> 
  <p><%= raw truncate("#{strip_tags(post.content)}", length: 300, separator: ' ') %></p>
</div>

app/views/posts/edit.html.erb
<% provide(:title, "Edit News Entry") %>
<div class="jumbotron">
  <div class="container">
    <h1>Edit Blog Entry</h1>
  </div>
</div>
<div class="container">
  <%= form_for @post, html: {role: 'form'} do |f| %>
    <%= render 'fields', f: f %>
    <br/>
    <%= f.submit "Submit Changes!", class: "btn btn-large btn-primary" %>
    <%= f.submit "Cancel", data: { confirm: "All changes will be lost.  Are you sure?" } %>
  <% end %>
</div>


<script>
  $('.nav-pills li a.blog').addClass('active');
</script>

app/views/posts/index.html.erb
<% provide(:title, 'News and Updates') %>
<div class="jumbotron">
  <div class="container">
    <h1>
      News 
      <%= link_to image_tag('RSS.png'), posts_url(format: 'atom'), target: '_blank', id: 'rss', title: 'Atom/RSS feed' %>
    </h1>
    <p>ReThink. ReStore. ReUse.</p>
  </div>
</div>  

<div class="container">
  <%= render @posts %>
  <%= paginate @posts %>
  <% if current_user && current_user.admin? %>
    <hr>
    <h3>Admin Actions</h3>
    <%= link_to 'Update Feeds', update_feed_path, class: 'btn btn-primary' %>
    <%= link_to "Post New Entry", new_post_path, class: 'btn btn-success' %>
    <h4>Add a feed from another site (needs testing from development, first)</h4>
    <div><%= render 'add' %></div>
  <% end %>
</div>

<script>
  $('.nav-pills li a.blog').addClass('active');
</script>

app/views/posts/new.html.erb
<% provide(:title, 'Post to Blog') %>
<div class="jumbotron">
  <div class="container">
    <h1>New Blog Entry</h1>
  </div>
</div>
<div class='container'>
  <%= form_for @post, html: {role: 'form'} do |f| %>
    <%= render 'fields', f: f %>
    <br/>
    <%= f.submit "Submit Article!", class: "btn btn-large btn-primary" %>
    <%= f.submit "Cancel", data: { confirm: "All changes will be lost.  Are you sure?" } %>
  <% end %>
</div>


<script>
  $('.nav-pills li a.blog').addClass('active');
</script>

app/views/posts/show.html.erb
<% provide(:title, "#{@post.title}") %>
<div class="jumbotron">
  <div class="container">
    <h1><%= @post.title %></h1>
    <% if @post.feed.id != 1 %>
    <p>&nbsp;&nbsp;&nbsp;from <%= @post.feed.url %></p>
    <% end %>
    <p><small>
      <% if @post.updated_at > @post.published_at %>
        updated <%= time_ago_in_words(@post.updated_at) %> ago
      <% else %>
        posted <%= time_ago_in_words(@post.created_at) %> ago
      <% end %>
      by <%= @post.user ? @post.user.name : @post.author %>
    </small></p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-10">
      <p><%= raw parse_links(@post.content) %></p>
    </div>
    <div class='col-sm-2'>
      <%= render @categories %>
      <% if signed_in? && current_user.admin? %>
        <br/><br/>
        <%= link_to "Edit Post", edit_post_path %> | <%= link_to "Delete Post", @post, method: :delete, data: { confirm: "You're sure you want to DELETE the post '#{@post.title}'?" } %>
      <% end %>
    </div>
  </div>
  
</div>


<script>
  $('.nav-pills li a.blog').addClass('active');
</script>