config/routes.rb
Erbv2::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :users
  resources :companies, path: 'our-customers' do
    member { get :snippet }
  end
  resources :posts, path: :news, defaults: { format: 'html' }
  resources :feeds
  resources :categories
  resources :boxes do
    collection { post :import }
    resources :unique_numbers, path: 'uin' do
      resources :locations
    end
  end
  resources :quotes, only: [:create]
  resources :orders
  resources :order_details
  resources :trips
  resources :sessions, only: [:new, :create, :destroy]
  resources :mailings, only: [:create, :index]
  resources :password_resets

  root                              to: 'pages#home'
  match '/company-profile',         to: 'pages#company-profile', as: :about
  match '/contact',                 to: 'pages#contact'
  match '/what-people-are-saying',  to: 'pages#testimonials', as: :testimonials
  match '/reusable-boxes',          to: 'pages#reusable-boxes', as: :reuse
  match '/methodology',             to: 'pages#methodology', as: :restore
  match '/sustainability',          to: 'pages#sustainability', as: :rethink
  match '/privacy',                 to: 'pages#privacy'
  match '/software',                to: 'pages#software'
  match '/use',                     to: 'pages#terms-of-use'
  match '/shipping-containers',     to: 'pages#shipping-containers', as: :shipping
  match '/tape',                    to: 'pages#tape'
  match '/signup',                  to: 'users#new'
  match '/signin',                  to: 'sessions#new'
  match '/signout',                 to: 'sessions#destroy', via: :delete
  match '/resources',               to: 'pages#resources'
  match '/savings',                 to: 'pages#cost-savings'
  match '/update-feed',             to: 'posts#feed', as: :update_feed
  match '/track',                   to: 'boxes#track', as: :track_box
  match '/erb',                     to: 'companies#erb'
  match '/calc',                    to: 'boxes#calc'
  match '/box-detail',              to: 'boxes#detail', as: :box_detail
  match '/import-locations',        to: 'locations#import', as: :import_locations

end

app/views/layouts/_errors.html.erb
 <div class='container'>
  <div class='row'>
    <div class='col-md-8 col-md-offset-2'>
      <% flash.each do |key, value| %>
        <div class="alert <%= flash_class(key) %>">
          <%= button_tag('&times;'.html_safe, class: 'close', data: {dismiss: 'alert'}, 'aria-hidden' => 'true') %>
          <%= value %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>
      <%= link_to image_tag("footer_logo.png", alt: "Eco Rebox"), root_path, class: "mainlogo" %>
      &nbsp;&nbsp;&copy; 2013 Eco ReBox, LLC. 
      &nbsp;|&nbsp; <%= link_to 'Privacy', privacy_path %>
      &nbsp;|&nbsp; <%= link_to 'Terms', use_path %>
      &nbsp;|&nbsp; <%= link_to 'Contact', contact_path %>
    </p>
    <%= yield :scripts %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-navbar-collapse1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("erb_logo.png", alt: "Eco Rebox"), root_path, class: "mainlogo navbar-brand" %>

      <div class="collapse navbar-collapse" id="bs-navbar-collapse1">
        <ul class="nav nav-pills pull-right">
          <li><%= link_to 'Home', root_path, class: 'first' %></li>
          <li><%= link_to 'News', posts_path, class: 'blog' %></li>
          <li class="dropdown second">
            <a href="about" class="dropdown-toggle" data-toggle="dropdown">
              About <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Company Profile', about_path %></li>
              <li><%= link_to 'Our Customers', companies_path %></li>
              <li><%= link_to 'What People Are Saying', testimonials_path %></li>
            </ul>
          </li>
          <li class="dropdown third">
            <a href="logistics" class="dropdown-toggle" data-toggle="dropdown">
              Solutions <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Software', software_path %></li>
              <li><%= link_to 'Sustainability', rethink_path %></li>
              <li><%= link_to 'Logistics & Methodology', restore_path %></li>
            </ul>
          </li>
          <li class="dropdown fourth">
            <a href="products" class="dropdown-toggle" data-toggle="dropdown">
              Products <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Reusable Boxes', reuse_path %></li>
              <li><%= link_to 'Shipping Containers', shipping_path %></li>
              <li><%= link_to 'Tape', tape_path %></li>
            </ul>
          </li>
          <li><%= link_to "Contact", contact_path, class: 'fifth' %></li>
          <% if signed_in? %>
          <li class="dropdown sixth">
            <a href="user" class="dropdown-toggle" data-toggle="dropdown">
              My Account <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Dashboard", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
            </ul>
          </li>
          <% else %>
          <li><a href="#signinModal" role="button" data-toggle="modal">Sign in</a></li>
          <% end %>
        </ul>
      </div> <!--/#bs-navbar-collapse1 -->
    </div>
  </div> <!--/.container -->
</nav>

<!-- Modal -->
<div id="signinModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="signinModallLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="signinModallLabel">Sign into Eco ReBox</h3>
      </div>
      <div class="modal-body">
        <%= render 'sessions/signin' %>
      </div>
      <div class="modal-footer">
        <div class="col-sm-offset-2 col-sm-10">
          <p class='pull-left'><%=link_to 'forgot your password?', new_password_reset_path %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!--[if lte IE 8]>
<script language="javascript" type="text/javascript" src="excanvas.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <% set_meta_tags title: full_title(yield(:title)) %>
    <% set_meta_tags viewport: 'width=device-width, initial-scale=1.0' %>
    <% set_meta_tags keywords: %w[reusable green box plastic packaging] %>
    <% set_meta_tags description: 'Eco ReBox supplies reusable plastic boxes to companies wanting to save the environment, and money.' %>
    <% set_meta_tags canonical: request.host_with_port %>
    <%= display_meta_tags %>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= auto_discovery_link_tag :atom, "/news.atom" %>
    <%= auto_discovery_link_tag :rss, "/news.rss" %>
    <%= render 'layouts/shim' %>
    <% if Rails.env.production? %>
      <script>
        (function(i,s,o,g,r,a,m){
          i['GoogleAnalyticsObject']=r;
          i[r]=i[r] || function(){ (i[r].q=i[r].q||[]).push(arguments) },
          i[r].l=1*new Date();
          a=s.createElement(o), m=s.getElementsByTagName(o)[0];
          a.async=1;
          a.src=g;
          m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-42828235-1', 'ecorebox.com');
        ga('send', 'pageview');
      </script>
    <% end %>
  </head>
  <body>
  <div id="fb-root"></div>
	<script>
    (function(d, s, id) {
  	  var js, fjs = d.getElementsByTagName(s)[0];
  	  if (d.getElementById(id)) return;
  	  js = d.createElement(s); js.id = id;
  	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=1450913535135699";
  	  fjs.parentNode.insertBefore(js, fjs);
  	}(document, 'script', 'facebook-jssdk'));
  </script>
    <div class='wrapper'>
      <%= render 'layouts/header' %>
      <%= render 'layouts/errors' %>
      <div class='content'>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>